<#
.SYNOPSIS
Flags GetRuntimeData() call sites in a consumer project's source that may need a
REL::Module::IsVR() gate, because their receiver's class also exposes a hand-written
GetVRRuntimeData() that returns a differently-laid-out struct (extra leading fields on VR).

.DESCRIPTION
CommonLibSSE-NG has two distinct GetRuntimeData() patterns:
  - SAFE (single accessor): generated by the RUNTIME_DATA_ACCESSOR macro, which picks the
    SE/VR byte offset internally via REL::RelocateMember(this, SEOffset, VROffset) and
    returns ONE struct type either way (e.g. RE::BSGraphics::Renderer::GetRuntimeData()).
    No caller-side branching needed.
  - DANGEROUS (hand-written pair): the class also declares GetVRRuntimeData(), returning a
    genuinely different struct type (VR has extra leading fields, so field offsets differ).
    GetRuntimeData()/GetVRRuntimeData() do NOT branch internally -- the CALLER must pick the
    right one via REL::Module::IsVR() / an equivalent runtime flag, or every field read/write
    silently lands on the wrong bytes.

This script auto-derives the "dangerous" class list from CommonLibSSE-NG's own headers (any
class/struct whose own file declares GetVRRuntimeData()), resolves receiver names to that
list in the TARGET project via explicit `RE::ClassName* name` declarations plus simple
`auto x = y;` alias propagation, then flags GetRuntimeData() calls on a resolved receiver
with no IsVR()/isVR nearby. It is a lint, not a prover: name-based receiver resolution can
both miss real cases (a receiver whose type never appears as an explicit `RE::Class*`/`&`
declaration anywhere, only ever behind `auto` with no traceable alias) and produce occasional
false positives (an unrelated local reusing a name like a dangerous class's), so a clean run
is not a proof and a flagged line still needs a human read before concluding it's a real bug.

Any CommonLibSSE-NG/CommonLibVR consumer can run this against their own source tree via
-ConsumerSrcRoot; it needs nothing project-specific beyond that path.

.PARAMETER CommonLibInclude
Path to CommonLibSSE-NG's include/ directory (default: this repo's own include/, since the
dangerous-class derivation only ever reads CommonLib's own headers).

.PARAMETER ConsumerSrcRoot
Source directory to scan for call sites (default: this repo's own src/, for self-checking;
override to point at any downstream project's source tree).

.PARAMETER ContextLines
How many lines before/after a call site to search for an IsVR()/isVR gate (default 20).

.EXAMPLE
./scripts/check-vr-runtime-data.ps1 -ConsumerSrcRoot C:\MyMod\src
#>
param(
    [string]$CommonLibInclude = (Join-Path (Split-Path -Parent $PSScriptRoot) "include"),
    [string]$ConsumerSrcRoot = (Join-Path (Split-Path -Parent $PSScriptRoot) "src"),
    [int]$ContextLines = 20
)

if (-not (Test-Path $CommonLibInclude)) {
    Write-Error "CommonLibSSE-NG include dir not found at $CommonLibInclude"
    exit 1
}
if (-not (Test-Path $ConsumerSrcRoot)) {
    Write-Error "Consumer src dir not found at $ConsumerSrcRoot"
    exit 1
}

# --- Step 1: derive the dangerous class list from CommonLibSSE-NG headers ---
# Heuristic: CommonLibSSE-NG is one-primary-class-per-file; a header declaring
# GetVRRuntimeData() names its class the same as the file stem in the overwhelming
# majority of cases (confirmed: RendererShadowState.h, ImageSpaceManager.h, PlayerCamera.h,
# NiCamera.h, BSShaderAccumulator.h, BSShadowLight.h, ...). Excludes the macro-definition
# files themselves (RuntimeDataAccessors.h, Common.h), which are not classes.
$excludeFiles = @("RuntimeDataAccessors.h", "Common.h")
$dangerousFiles = Get-ChildItem -Path $CommonLibInclude -Recurse -Filter "*.h" |
    Where-Object { $excludeFiles -notcontains $_.Name } |
    Where-Object { Select-String -Path $_.FullName -Pattern "GetVRRuntimeData" -Quiet }

$dangerousClasses = $dangerousFiles | ForEach-Object { $_.BaseName } | Sort-Object -Unique

Write-Host "Dangerous classes (declare GetVRRuntimeData, need caller-side IsVR gating):" -ForegroundColor Cyan
$dangerousClasses | ForEach-Object { Write-Host "  - $_" }
Write-Host ""

$sourceFiles = Get-ChildItem -Path $ConsumerSrcRoot -Recurse -Include "*.cpp", "*.h", "*.hpp"
$dangerousPattern = ($dangerousClasses | ForEach-Object { [regex]::Escape($_) }) -join "|"

# Read each source file once; the declaration, alias, and scan passes below all reuse this
# instead of re-reading from disk 3x per file.
$fileLines = @{}
foreach ($file in $sourceFiles) {
    $fileLines[$file.FullName] = Get-Content -Path $file.FullName
}

# --- Step 2: resolve receiver names -> dangerous class, project-wide ---
# Pass A: explicit `RE::(...::)*ClassName [*&] name` declarations (globals, locals, params).
# Pass B: `auto name = <knownGlobalOrLocal>;` aliasing (a common idiom, e.g.
#   `auto shadowState = globals::game::shadowState;`) -- propagated by name, not scope, since
#   this is a lint (flag for review), not a real type resolution: a same-named local shadowing
#   an unrelated type would cause a false positive, which is an acceptable cost here.
$declPattern = "RE::(?:\w+::)*(?<cls>$dangerousPattern)\s*[*&]\s*(?<name>[A-Za-z_][A-Za-z0-9_]*)"
$receiverType = @{}
foreach ($file in $sourceFiles) {
    foreach ($line in $fileLines[$file.FullName]) {
        foreach ($dm in [regex]::Matches($line, $declPattern)) {
            $receiverType[$dm.Groups["name"].Value] = $dm.Groups["cls"].Value
        }
    }
}
$aliasPattern = 'auto\s+(?<lhs>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?:[A-Za-z_][A-Za-z0-9_]*::)*(?<rhs>[A-Za-z_][A-Za-z0-9_]*)\s*;'
foreach ($file in $sourceFiles) {
    foreach ($line in $fileLines[$file.FullName]) {
        $am = [regex]::Match($line, $aliasPattern)
        if ($am.Success -and $receiverType.ContainsKey($am.Groups["rhs"].Value) -and -not $receiverType.ContainsKey($am.Groups["lhs"].Value)) {
            $receiverType[$am.Groups["lhs"].Value] = $receiverType[$am.Groups["rhs"].Value]
        }
    }
}

Write-Host "Resolved $($receiverType.Count) receiver name(s) to a dangerous class." -ForegroundColor Cyan
Write-Host ""

# --- Step 3: scan consumer source for GetRuntimeData() call sites on resolved receivers ---
$callSitePattern = '(?<receiver>[A-Za-z_][A-Za-z0-9_]*)\s*(?:\.|->)\s*GetRuntimeData\s*\('
$vrGatePattern = 'IsVR\s*\(|(?<![A-Za-z0-9_])isVR(?![A-Za-z0-9_])'

$flagged = @()
foreach ($file in $sourceFiles) {
    $lines = $fileLines[$file.FullName]
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        $m = [regex]::Match($line, $callSitePattern)
        if (-not $m.Success) { continue }
        $receiver = $m.Groups["receiver"].Value
        if (-not $receiverType.ContainsKey($receiver)) { continue }

        $lo = [Math]::Max(0, $i - $ContextLines)
        $hi = [Math]::Min($lines.Count - 1, $i + $ContextLines)
        $context = ($lines[$lo..$hi] -join "`n")

        if ([regex]::IsMatch($context, $vrGatePattern)) { continue }

        $flagged += [PSCustomObject]@{
            File     = $file.FullName.Substring($ConsumerSrcRoot.Length + 1)
            Line     = $i + 1
            Receiver = $receiver
            Class    = $receiverType[$receiver]
            Text     = $line.Trim()
        }
    }
}

if ($flagged.Count -eq 0) {
    Write-Host "No unguarded GetRuntimeData() call sites found." -ForegroundColor Green
    exit 0
}

Write-Host "Unguarded GetRuntimeData() call sites (no IsVR()/isVR within +/-$ContextLines lines):" -ForegroundColor Yellow
Write-Host "Review each: confirm the receiver's class isn't in the dangerous list above, or add an IsVR() branch." -ForegroundColor Yellow
Write-Host ""
foreach ($f in $flagged) {
    Write-Host "$($f.File):$($f.Line)" -ForegroundColor Red
    Write-Host "    receiver: $($f.Receiver) (RE::$($f.Class))"
    Write-Host "    $($f.Text)"
}

Write-Host ""
Write-Host "$($flagged.Count) flagged call site(s)." -ForegroundColor Yellow
exit 1
